AWSTemplateFormatVersion: "2010-09-09"
Description: Provision of SubscriptionFileterRole

Parameters:
  DeliveryStreamName01:
    Description: DeliveryStreamName01.
    Type: String

Resources:
  SubscriptionFileterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: subscription_filter_role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub "logs.${AWS::Region}.amazonaws.com"
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: subscription_filter_policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - firehose:PutRecord
                  - firehose:PutRecords
                Resource: !Sub "arn:aws:firehose:${AWS::Region}:${AWS::AccountId}:deliverystream/${DeliveryStreamName01}"

Outputs:
  SubscriptionFileterRole:
    Value: !GetAtt SubscriptionFileterRole.Arn
    Export:
      Name: SubscriptionFileterRole