AWSTemplateFormatVersion: "2010-09-09"
Description: Provision of S3ALB

Parameters:
  sysname:
    Type: String

  BucketNameALB:
    Type: String

Resources:
  S3ALB:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketNameALB

  S3ALBPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3ALB
      PolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal: 
              AWS: arn:aws:iam::582318560864:root
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${BucketNameALB}/*
  
  LambdaUsedToCleanUp:
    Type: Custom::cleanupbucket
    Properties:
      ServiceToken: {Fn::ImportValue: !Sub "${sysname}-s3delete-lambda-function"}
      BucketName: !Ref S3ALB

Outputs:
  S3ALB:
    Value: !Ref S3ALB #上位テンプレートへ出力