AWSTemplateFormatVersion: "2010-09-09"
Description: Provision of FirehoseDeliveryRole

Parameters:
  BucketNameEC2:
    Type: String

  RoleName:
    Type: String

  PolicyName:
    Type: String

Resources:
  DeliverlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Ref PolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:PutObject
            Resource:
              - !Sub "arn:aws:s3:::${BucketNameEC2}"
              - !Sub "arn:aws:s3:::${BucketNameEC2}*"
      Roles:
        - !Ref DeliveryRole

  DeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref AWS::AccountId

Outputs:
  FirehoseDeliveryRole:
    Value: !GetAtt DeliveryRole.Arn