AWSTemplateFormatVersion: "2010-09-09"
Description: CloudWatch Metrics,Fileter,Alarm,Health

Parameters:
  sysname:
    Type: String

  SNSTopicName:
    Type: String
    Default: alarm-topic
  
  email:
    Type: String

Resources:
  AlarmNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${sysname}-${SNSTopicName}
      DisplayName: !Sub ${sysname}-${SNSTopicName}
      Subscription:
        - Endpoint: !Ref email
          Protocol: email

  #EC2 ステータスチェック
  EC2StatusCheckFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref AlarmNotificationTopic
      AlarmName: !Sub ${sysname}-ec2-statuscheck-alarm
      MetricName: StatusCheckFailed
      Namespace: AWS/EC2
      Statistic: Average
      Period: 60 
      EvaluationPeriods: 1 # 閾値超過回数
      Threshold: 0 # 閾値
      TreatMissingData: breaching # 欠落データは不良（EC2停止時にもアラート）
      ComparisonOperator: GreaterThanThreshold # 閾値より大きい
      Dimensions: # プッシュ時の付加情報
        - Name: InstanceId
          Value: {Fn::ImportValue: !Sub "${sysname}-ec2"}

#EC2 メトリクスフィルタ Error検知
  EC2ErrorMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterName: !Sub ${sysname}-ec2-syslogerror-filter
      FilterPattern: "?ERROR ?Error ?error"
      LogGroupName: /var/log/messages
      MetricTransformations:
        - MetricName: !Sub ${sysname}-ec2-syslogerror-metric
          MetricNamespace: LogMetrics
          MetricValue: 1
  
  EC2ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref AlarmNotificationTopic
      AlarmName: !Sub ${sysname}-ec2-syslogerror-alarm
      MetricName: !Sub ${sysname}-ec2-syslogerror-metric
      Namespace: LogMetrics
      Statistic: Average
      Period: 60 
      EvaluationPeriods: 1 # 閾値超過回数
      Threshold: 0 # 閾値
      ComparisonOperator: GreaterThanThreshold # 閾値より大きい

#Health（メンテナンス等） 通知
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${sysname}-notify-healthevent-rule
      EventPattern: '{"source":["aws.health"]}'
      State: ENABLED
      Targets:
        - Arn: !Ref AlarmNotificationTopic
          Id: "Id123"
      EventBusName: default


