AWSTemplateFormatVersion: "2010-09-09"
Description: lambda to delete object in S3

Resources:
  s3deletelambda:
    Type: AWS::IAM::Role
    Properties:
      RoleName: s3_delete_lambda_role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: s3delete
      Role: !GetAtt s3deletelambda.Arn
      Runtime: python3.7
      Handler: index.lambda_handler
      Timeout: 600
      Code:
        ZipFile: |
          #!/usr/bin/env python
          # -*- coding: utf-8 -*-
      
          import json
          import boto3
          import requests # ベンダーバージョンのリクエストを削除
      
          def lambda_handler(event, context):
              try:
                  bucket = event['ResourceProperties']['BucketName']
          
                  if event['RequestType'] == 'Delete':
                      s3 = boto3.resource('s3')
                      bucket = s3.Bucket(bucket)
                      for obj in bucket.objects.filter():
                          s3.Object(bucket.name, obj.key).delete()
                          bucket.object_versions.delete() # コード追加
          
                  sendResponseCfn(event, context, "SUCCESS")
              except Exception as e:
                  print(e)
                  sendResponseCfn(event, context, "FAILED")
          
          def sendResponseCfn(event, context, responseStatus):
              response_body = {'Status': responseStatus,
                               'Reason': 'Log stream name: ' + context.log_stream_name,
                               'PhysicalResourceId': context.log_stream_name,
                               'StackId': event['StackId'],
                               'RequestId': event['RequestId'],
                               'LogicalResourceId': event['LogicalResourceId'],
                               'Data': json.loads("{}")}
              requests.put(event['ResponseURL'], data=json.dumps(response_body))

Outputs:
  LambdaFunction:
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: LambdaFunction-cfn-arn