AWSTemplateFormatVersion: "2010-09-09"
Description: VPC,Subnet

Parameters:
  sysname:
    Type: String

  BucketNameFlowLogs:
    Type: String

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      Tags:
        - Key: Name
          Value: !Sub ${sysname}-vpc
  
  S3FlowLog:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${sysname}-${BucketNameFlowLogs}
  
  FlowLogToS3:
    Type: AWS::EC2::FlowLog
    DependsOn:
      - S3FlowLog
    Properties:
      LogDestination: !GetAtt S3FlowLog.Arn
      LogDestinationType: s3
      ResourceId: !Ref VPC
      ResourceType: VPC
      TrafficType: ALL
  
  LambdaUsedToCleanUp:
    Type: Custom::cleanupbucket
    Properties:
      ServiceToken: {Fn::ImportValue: !Sub "${sysname}-s3delete-lambda-function"}
      BucketName: !Ref S3FlowLog

  # IGW
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${sysname}-igw
  
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW

  # PubSub1
  PubSub1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref VPC
      CidrBlock: 10.1.1.0/24
      Tags:
        - Key: Name
          Value: !Sub ${sysname}-pubsub1

  PubSub1RT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${sysname}-pubsub1-rt
  
  PubSub1RTTarget:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PubSub1RT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  AssoPubSub1RT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PubSub1
      RouteTableId: !Ref PubSub1RT

  # PubSub2
  PubSub2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref VPC
      CidrBlock: 10.1.2.0/24
      Tags:
        - Key: Name
          Value: !Sub ${sysname}-pubsub2

  # Nat Gateway
  NatGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt: # テンプレート内のリソースから属性の値を返す
          - NatGatewayEIP
          - AllocationId # EIPのID
      SubnetId: !Ref PubSub1
      Tags:
        - Key: Name
          Value: !Sub ${sysname}-natgateway

  # PriSub
  PriSub:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref VPC
      CidrBlock: 10.1.3.0/24
      Tags:
        - Key: Name
          Value: !Sub ${sysname}-prisub
  
  PriSubRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${sysname}-prisub-rt

  PriSubRTTarget:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PriSubRT
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  AssoPriSubRT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PriSub
      RouteTableId: !Ref PriSubRT

Outputs:
  Vpc:
    Value: !Ref VPC
    Export:
      Name: !Sub ${sysname}-vpc
  
  PubSubA:
    Value: !Ref PubSub1
    Export:
      Name: !Sub ${sysname}-pubsub1
  
  PubSubB:
    Value: !Ref PubSub2
    Export:
      Name: !Sub ${sysname}-pubsub2
  
  PriSub:
    Value: !Ref PriSub
    Export:
      Name: !Sub ${sysname}-prisub