AWSTemplateFormatVersion: 2010-09-09
Description: Create S3

Parameters:
  BucketNameEC2:
    Type: String
    Description: A name for the EC2 bucket.

Resources:
  S3EC2:
    Type: AWS::S3::Bucket
    Properties:
         BucketName: !Ref BucketNameEC2
